import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:meshlink_app/core/capability_token.dart';
import 'package:meshlink_app/core/friend_wire.dart';
import 'package:meshlink_app/core/sealed.dart';

Uint8List _fromHex(String hex) {
  final out = Uint8List(hex.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

String _hex(List<int> bytes) =>
    bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();

/// Replays test/fixtures/friendship_parity_vectors.json, generated by
/// tool/gen_friendship_vectors.py from the Python reference in meshlink-core:
/// tokens, sealed envelopes, and friend payloads produced by Python must be
/// byte-compatible with this Dart port (phones talk to Python nodes).
void main() {
  final fixture = jsonDecode(
    File('test/fixtures/friendship_parity_vectors.json').readAsStringSync(),
  ) as Map<String, dynamic>;

  test('Dart mints the byte-identical capability token', () async {
    final v = fixture['token'] as Map<String, dynamic>;
    final issuerKp = await Ed25519()
        .newKeyPairFromSeed(_fromHex(v['issuer_ed25519_seed_hex'] as String));
    final issuerPub =
        Uint8List.fromList((await issuerKp.extractPublicKey()).bytes);
    expect(_hex(issuerPub), v['issuer_ed25519_pub_hex'],
        reason: 'seed-derived public keys must agree');

    final token = await issueToken(
      issuerKeyPair: issuerKp,
      issuerPub: issuerPub,
      granteeEd25519Pub: _fromHex(v['grantee_ed25519_pub_hex'] as String),
      issuedAt: v['issued_at'] as int,
      expiry: Duration(seconds: v['expiry_s'] as int),
      nonce: _fromHex(v['nonce_hex'] as String),
    );
    // Ed25519 signatures are deterministic (RFC 8032), so byte equality is
    // the strongest possible parity statement.
    expect(_hex(token), v['token_hex']);
  });

  test('Dart verifies the Python-minted token', () async {
    final v = fixture['token'] as Map<String, dynamic>;
    final ok = await verifyToken(
      _fromHex(v['token_hex'] as String),
      _fromHex(v['issuer_ed25519_pub_hex'] as String),
      _fromHex(v['grantee_ed25519_pub_hex'] as String),
      (v['issued_at'] as int) + 60,
    );
    expect(ok, isTrue);
  });

  test('Dart unseals a Python-sealed envelope', () async {
    final v = fixture['sealed'] as Map<String, dynamic>;
    final recipient = await X25519()
        .newKeyPairFromSeed(_fromHex(v['recipient_x25519_seed_hex'] as String));
    final plaintext =
        await unseal(_fromHex(v['sealed_hex'] as String), recipient);
    expect(_hex(plaintext), v['plaintext_hex']);
  });

  test('Dart decodes a Python-encoded FRIEND_REQUEST', () async {
    final v = fixture['friend_request'] as Map<String, dynamic>;
    final raw = _fromHex(v['payload_hex'] as String);
    expect(_hex(recipientHintOf(raw)), v['hint_hex']);

    final recipient = await X25519()
        .newKeyPairFromSeed(_fromHex(v['recipient_x25519_seed_hex'] as String));
    final decoded = await decodeFriendRequest(raw, recipient);
    expect(decoded.username, v['username']);
    expect(_hex(decoded.curve25519Pub), v['sender_curve25519_pub_hex']);
    expect(_hex(decoded.ed25519Pub), v['sender_ed25519_pub_hex']);
  });

  test('Dart decodes a Python-encoded LOCATION_RESPONSE (the node path)',
      () async {
    final v = fixture['location_response'] as Map<String, dynamic>;
    final requester = await X25519()
        .newKeyPairFromSeed(_fromHex(v['requester_x25519_seed_hex'] as String));
    final decoded = await decodeLocationResponse(
        _fromHex(v['payload_hex'] as String), requester);
    expect(decoded.latMicrodeg, v['lat_microdeg']);
    expect(decoded.lonMicrodeg, v['lon_microdeg']);
    expect(decoded.accuracyM, v['accuracy_m']);
    expect(decoded.beaconAgeS, v['beacon_age_s']);
    expect(decoded.zoneId, v['zone_id']);
  });
}
