import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:meshlink_app/core/pipeline.dart';

Uint8List _fromHex(String hex) {
  final out = Uint8List(hex.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

/// Replays the vectors generated by tool/gen_parity_vectors.py from the
/// Python reference pipeline in meshlink-core, asserting the Dart port
/// produces identical outcomes, drop-reason strings, and parsed fields.
void main() {
  final fixture = jsonDecode(
    File('test/fixtures/parity_vectors.json').readAsStringSync(),
  ) as Map<String, dynamic>;
  final vectors = (fixture['vectors'] as List).cast<Map<String, dynamic>>();

  // One pipeline for all vectors, in order — the duplicate_msg_id vector
  // relies on dedup state written by valid_text_deliver, exactly as in the
  // Python generation run. Signature verification off: the Python reference
  // stubs step 6, and these vectors carry zeroed signatures.
  final pipeline = RelayPipeline(
    now: () => vectors.first['fixed_now'] as int,
    verifySignatures: false,
  );

  test('Dart pipeline matches Python reference on all vectors', () async {
    for (final vector in vectors) {
      final name = vector['name'] as String;
      final result = await pipeline.process(_fromHex(vector['raw_hex'] as String));

      expect(result.outcome.value, vector['outcome'], reason: name);
      expect(result.dropReason, vector['drop_reason'], reason: name);

      final parsed = vector['parsed'] as Map<String, dynamic>?;
      if (parsed != null) {
        final m = result.message!;
        String hex(Uint8List b) =>
            b.map((x) => x.toRadixString(16).padLeft(2, '0')).join();
        expect(hex(m.msgId), parsed['msg_id_hex'], reason: name);
        expect(hex(m.senderKey), parsed['sender_key_hex'], reason: name);
        expect(hex(m.ephemId), parsed['ephem_id_hex'], reason: name);
        expect(m.timestamp, parsed['timestamp'], reason: name);
        expect(m.ttl, parsed['ttl'], reason: name);
        expect(m.sprayL, parsed['spray_l'], reason: name);
        expect(m.zoneId, parsed['zone_id'], reason: name);
        expect(m.msgType, parsed['msg_type'], reason: name);
        expect(m.payloadLen, parsed['payload_len'], reason: name);
        expect(hex(m.payload), parsed['payload_hex'], reason: name);
        expect(hex(m.signature), parsed['signature_hex'], reason: name);
      }
    }
  });
}
